/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { CategoryWhereUniqueInput } from "../../category/base/CategoryWhereUniqueInput";
import { Type } from "class-transformer";
import { FavoriteCreateNestedManyWithoutProductsInput } from "./FavoriteCreateNestedManyWithoutProductsInput";
import { DiscountCodeCreateNestedManyWithoutProductsInput } from "./DiscountCodeCreateNestedManyWithoutProductsInput";

@InputType()
class ProductCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  photo?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  purchaseLinks?: string | null;

  @ApiProperty({
    required: false,
    type: () => CategoryWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => CategoryWhereUniqueInput)
  @IsOptional()
  @Field(() => CategoryWhereUniqueInput, {
    nullable: true,
  })
  category?: CategoryWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FavoriteCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => FavoriteCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => FavoriteCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  favorites?: FavoriteCreateNestedManyWithoutProductsInput;

  @ApiProperty({
    required: false,
    type: () => DiscountCodeCreateNestedManyWithoutProductsInput,
  })
  @ValidateNested()
  @Type(() => DiscountCodeCreateNestedManyWithoutProductsInput)
  @IsOptional()
  @Field(() => DiscountCodeCreateNestedManyWithoutProductsInput, {
    nullable: true,
  })
  discountCodes?: DiscountCodeCreateNestedManyWithoutProductsInput;
}

export { ProductCreateInput as ProductCreateInput };
